name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronized]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge" # The bot will only merge if the PR has this label
          MERGE_METHOD: "merge"
